---
name: h99
extra-source-files: readme.rst
dependencies: base
library:
  source-dirs: src
tests:
  one:
    main: Spec.hs
    source-dirs: test/one
    dependencies: [h99, hspec, QuickCheck]
  two:
    main: Spec.hs
    source-dirs: test/two
    dependencies: [h99, hspec, QuickCheck]
  three:
    main: Spec.hs
    source-dirs: test/three
    dependencies: [h99, hspec, QuickCheck]
  four:
    main: Spec.hs
    source-dirs: test/four
    dependencies: [h99, hspec, QuickCheck]
  five:
    main: Spec.hs
    source-dirs: test/five
    dependencies: [h99, hspec, QuickCheck]
  six:
    main: Spec.hs
    source-dirs: test/six
    dependencies: [h99, hspec, QuickCheck]
...
